// refer to https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf
// section 10.2.1 for more info on the core algorithm

#include <stdint.h>
#include <string.h>

#define KEYLEN   16
#define BLOCKLEN 16
#define SEEDLEN  32

void aes128_encrypt_block(
    const uint8_t key[KEYLEN],
    const uint8_t input[BLOCKLEN],
    uint8_t output[BLOCKLEN]
);

typedef struct {
    uint8_t Key[KEYLEN];
    uint8_t V[BLOCKLEN];
} ctr_drbg_state;

// counter. to increment V 
static void increment_v(uint8_t V[BLOCKLEN])
{
    for (int i = BLOCKLEN - 1; i >= 0; i--) {
        V[i]++;

        if (V[i] != 0) {
            break;
        }
    }
}

static void ctr_drbg_update(
    ctr_drbg_state *state,
    const uint8_t provided_data[SEEDLEN])
{
    uint8_t temp[SEEDLEN];

    // generate 32 bytes using two AES blocks
    for (int i = 0; i < SEEDLEN; i += BLOCKLEN) {
        increment_v(state->V);

        aes128_encrypt_block(
            state->Key,
            state->V,
            &temp[i]
        );
    }

    // XOR the generated bytes with the seed material
    for (int i = 0; i < SEEDLEN; i++) {
        temp[i] ^= provided_data[i];
    }

    // update the key and counter V
    memcpy(state->Key, temp, KEYLEN);
    memcpy(state->V, &temp[KEYLEN], BLOCKLEN);
}

// initialize the ctr_drbg for its initialization function
// gets state (key 16bytes seed16bytes) entropy input(32 bytes seed)
void ctr_drbg_instantiate(
    ctr_drbg_state *state,
    const uint8_t entropy_input[SEEDLEN])
{
    // start with a zero Key and V
    memset(state->Key, 0, KEYLEN);
    memset(state->V, 0, BLOCKLEN);

    // use the entropy input as seed material
    ctr_drbg_update(state, entropy_input);
}


void ctr_drbg_generate(
    ctr_drbg_state *state,
    uint8_t output[KEYLEN])
{
    // Increment V and encrypt it to generate 16 bytes
    increment_v(state->V);
    aes128_encrypt_block(state->Key, state->V, output);

    // Update the state after generating output
    uint8_t provided_data[SEEDLEN] = {0};
    ctr_drbg_update(state, provided_data);
}